# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/adamchainz/django-upgrade
  rev: '1.24.0'
  hooks:
    - id: django-upgrade
      args: ['--target-version', '5.1']

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    - id: ruff-format

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: true
