[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = {{ cookiecutter.description | tojson }}
authors = [{name = {{ cookiecutter.author_name | tojson }}, email = {{ cookiecutter.author_email | tojson }}}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14.6,<3.15"
dependencies = [
    "django==6.1.1",
    "django-axes==8.3.1",
    "django-compressor==4.6.0",
    "django-extensions==4.1",
    "django-kronos==1.0",
    "django-loginas==0.3.14",
    "django-post-office==3.11.3",
    "django-secrets==3.0.5",
    "django-tasks-db==0.13.0",
    "djangorestframework==3.18.1",
    "gunicorn==26.2.0",
    "icecream==2.2.0",
    "pendulum==3.2.0",
    "pillow==12.3.0",
    "pypugjs==7.0.0",
    "requests==2.34.2",
    "sentry-sdk==2.70.0",
    "whitenoise==6.12.0",
    # django-model-utils - use this if a status field is needed and maybe also a status_changed field
]

{% if cookiecutter.repository_url %}
[project.urls]
repository = {{ cookiecutter.repository_url | tojson }}
{% endif %}

[dependency-groups]
dev = [
    "django-browser-reload==1.21.0",
    "django-debug-toolbar==8.0.0",
    "fab-classic==1.21.0",  # uv add --group dev "git+https://github.com/kakulukia/fab-classic.git#master" (ssh key fwding)
    "ipdb==0.13.13",
    "pre-commit==4.6.2",
    "ruff==0.16.9",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120
exclude = [
    "migrations",
    "node_modules",
    ".venv",
]

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]
